#!/bin/bash

set -e

beamup_dir=~/.beamup
symlink=/usr/local/bin/beamup


# Run everything inside a function to avoid creating
# a mess if the download fails halfway through.
install () {
  echo ""
  echo "Hello, this is the BeamUp installer."
  echo ""
  echo "This script will first remove everything in $beamup_dir/cli"
  echo "then install a fresh clone of the beamup/cli repo to $beamup_dir/cli"
  echo "and create a symlink in $symlink"
  echo ""

  # Detect if running in a TTY
  if [ -t 0 ]; then
    echo "Press CRTL+C to cancel installation now, or wait a few seconds to continue..."
    sleep 6
    echo ""
  fi

  # Start with a clean slate
  uninstall

  mkdir -p $beamup_dir/cli
  git clone https://github.com/beamup-io/cli $beamup_dir/cli
  chmod +x $beamup_dir/cli/beamup
  ln -s "$beamup_dir/cli/beamup" "$symlink" | path_fallback

  echo ""
  echo "Running \"beamup selftest\""
  echo ""

  beamup selftest
}

path_fallback () {
  echo "Could not create symlink - don't worry, you can still use"
  echo "BeamUp by adding this line to your ~/.bashrc file:"
  echo '  export PATH="$beamup_dir/cli:$PATH"'
}

uninstall() {
  if [ -L "$symlink" ]; then
    echo "Removing $symlink"
    rm $symlink
  fi

  if [ -d "$beamup_dir/cli" ]; then
    echo "Removing $beamup_dir/cli"
    rm -rf $beamup_dir/cli
  fi

}

cli_command=$1
case $cli_command in
  uninstall)
    uninstall
    ;;
  *)
    install
    ;;
esac
